server:
  port: 8082
  context-path: /consumer-b
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    pool:
      enabled: true
      max-connections: 10
    packages:
      trust-all: true

queueName: out.queue
topicName: out.topic