server:
  port: 8081
  context-path: /consumer-a
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    pool:
      enabled: true
      max-connections: 10

queueName: out.queue
topicName: out.topic